apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udr-config
  labels:
    epc-mode: udr
data:
  udr.yaml: |
    db_uri: mongodb://mongodb-svc/open5gs
    # logger:
    #  file: /var/log/open5gs/udr.log
    #  level: info   # fatal|error|warn|info(default)|debug|trace

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.
    #    peer: 64

    udr:
      sbi:
        server:
          - dev: eth0
            advertise: open5gs-udr-skupper
            # port: 7777
        client:
          # nrf:
          #   - uri: http://open5gs-nrf
          scp:
            - uri: http://open5gs-scp-skupper
