apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-amf-config
  labels:
    epc-mode: amf
data:
  amf.yaml: |
    logger:
    #  file: /var/log/open5gs/amf.log
      level: trace   # fatal|error|warn|info(default)|debug|trace

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.
    #    peer: 64

    amf:
      sbi:
        server:
          - dev: eth0
            advertise: open5gs-amf-skupper
            # port: 7777
        client:
          # nrf:
          #   - uri: http://open5gs-nrf
          scp:
            - uri: http://open5gs-scp-skupper
      ngap:
        server:
          - address: 0.0.0.0
      metrics:
        server:
          - address: 0.0.0.0
            port: 9090
      guami:
        - plmn_id:
            mcc: {{ .Values.core.mcc }}
            mnc: {{ .Values.core.mnc }}
          amf_id:
            region: 2
            set: 1
      tai:
        - plmn_id:
            mcc: {{ .Values.core.mcc }}
            mnc: {{ .Values.core.mnc }}
          tac: {{ .Values.core.tac }}
      plmn_support:
        - plmn_id:
            mcc: {{ .Values.core.mcc }}
            mnc: {{ .Values.core.mnc }}
          s_nssai:
            - sst: 1
              # sd: 1
      security:
        integrity_order : [ NIA2, NIA1, NIA0 ]
        ciphering_order : [ NEA0, NEA1, NEA2 ]
      network_name:
        full: Open5GS
        short: Next
      amf_name: open5gs-amf0
      time:
    #    t3502:
    #      value: 720   # 12 minutes * 60 = 720 seconds
        t3512:
          value: 540

    # nrf:
    #  sbi:
    #    name: open5gs-nrf
    # scp:
    #  sbi:
    #    name: open5gs-scp
