apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-ausf-config
  labels:
    epc-mode: ausf
data:
  ausf.yaml: |
    logger:
    #  file: /var/log/open5gs/ausf.log
      level: trace   # fatal|error|warn|info(default)|debug|trace

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.
    #    peer: 64

    ausf:
      sbi:
        server:
          - dev: eth0
            advertise: open5gs-ausf-skupper
            # port: 7777
        client:
          # nrf:
          #   - uri: http://open5gs-nrf
          scp:
            - uri: http://open5gs-scp-skupper
        # discovery:
        #   delegated: no
