apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-pcrf-config
  labels:
    epc-mode: pcrf
data:
  pcrf.yaml: |
    db_uri: mongodb://mongodb-svc-skupper/open5gs
    # logger:
    #  file: /var/log/open5gs/pcrf.log
    #  level: info   # fatal|error|warn|info(default)|debug|trace

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.
    #    peer: 64
    pcrf:
      freeDiameter: /etc/freeDiameter/pcrf.conf
