apiVersion: v1
kind: Service
metadata:
  name: open5gs-pcrf
  labels:
    epc-mode: pcrf
spec:
  selector:
    epc-mode: pcrf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-pcrf-deployment
  labels:
    epc-mode: pcrf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: pcrf
  template:
    metadata:
      labels:
        epc-mode: pcrf
    spec:
      containers:
        - name: pcrf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["open5gs-pcrfd", "-c", "/open5gs/config-map/pcrf.yaml"]
          volumeMounts:
          - name: open5gs-pcrf-config
            mountPath: /open5gs/config-map/pcrf.yaml
            subPath: "pcrf.yaml"
      volumes:
        - name: open5gs-pcrf-config
          configMap:
            name: open5gs-pcrf-config
