# Default values for Ue simulator.
ran:
  image:
    repository: quay.io/motohiroabe/ueransim
    pullPolicy: Always
    tag: "v3.2.6"
  amf:
    address: amf-open5gs-sctp
    port: 38412
    # address: 192.168.1.170
    # port: 30412 # node port
    # address: amf-open5gs-sctp # skupper
    # port: 8888  # skupper
  user:
    imsi: "imsi-208930000000001"
  tac: 7


# Default values for open5gs-epc-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

open5gs:
  image:
    repository: quay.io/motohiroabe/open5gs
    pullPolicy: Always
    tag: "v2.7.0"

mongodb:
  image:
    # repository: quay.io/motohiroabe/open5gs-mongodb
    # repository: mongo
    repository: free5gmano/nextepc-mongodb
    pullPolicy: IfNotPresent
    tag: "latest"


webui:
  image:
    repository: quay.io/motohiroabe/open5gs-webui
    pullPolicy: Always
    tag: "v2.7.0"
  ingress:
    enabled: false
    ## Ingress annotations done as key:value pairs
    ## For a full list of possible ingress annotations, please see
    ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md
    ##
    ## If tls is set to true, annotation ingress.kubernetes.io/secure-backends: "true" will automatically be set
    # annotations:
    #   kubernetes.io/ingress.class: nginx

    hosts:
      - name: open5gs-epc.local
        paths: ["/"]
        ## Set this to true in order to enable TLS on the ingress record
        tls: false

        ## Optionally specify the TLS hosts for the ingress record
        ## Useful when the Ingress controller supports www-redirection
        ## If not specified, the above host name will be used
        # tlsHosts:
        # - www.open5gs-epc.local
        # - open5gs-epc.local

        ## If TLS is set to true, you can declare what secret will store the key/certificate for TLS
        # tlsSecret: open5gs-epc.local-tls

dnn: internet

core:
  mcc: 208
  mnc: 93
  tac: 7

# Primary/Native kubernetes interface
k8s:
 interface: eth0
 advertise: 192.168.50.200

